version: '3'
services:
  web:
    build: .
    command: >
      bash -c '
         bundle exec rails s -b 0.0.0.0
      '
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - RACK_ENV=development
      - RAILS_ENV=development
    volumes:
      - .:/app
    depends_on:
      - db
  db:
    image: postgres:latest
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: my_rails_app
      POSTGRES_PASSWORD: my_rails_app_password

volumes:
  pgdata:
